version: '3'
services:
  web:
    build: 
    #where you want the context to be pulled from
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: 
    #where you want the context to be pulled from
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    #override command inside docker
    command: ["npm", "run", "test"]



